server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: 


  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create-drop
    show-sql: true


  h2:
    console:
      enabled: true
      path: /h2-console
      
      
logging:
  level:
    org.springframework.web: ERROR
    com.rbs.licensemanagement: DEBUG
  pattern:
    console: "%d{yyy-mm-dd HH:mm:ss} - %msg%n"
    file: "%d{yyy-mm-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: /var/log/license-managment/license-api.log